version: "3"

services:
    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 100:100
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - userservice
            - statusservice
            - storyservice

    userservice:
        build: ./UserService
        restart: unless-stopped
        depends_on:
            - userdb

    userdb:
        image: mongo:4.0-xenial
        ports: 
            - 27018:27017
        restart: unless-stopped
        volumes:
            - ./mongoUser:/data/db
    statusservice:
        build: ./StatusService
        restart: unless-stopped
        depends_on:
            - statusdb

    statusdb:
        image: mongo:4.0-xenial
        ports: 
            - 27019:27017
        restart: unless-stopped
        volumes:
            - ./mongoStatus:/data/db

    storyservice:
        build: ./StoryService
        restart: unless-stopped
        depends_on:
            - storydb
            - storyobjectdb

    storydb:
        image: mongo:4.0-xenial
        ports: 
            - 27020:27017
        restart: unless-stopped
        volumes:
            - ./mongoStory:/data/db

    storyobjectdb:
        image: minio/minio:latest
        ports:
            - 9000:9000
            - 9001:9001
        environment:
            - MINIO_ACCESS_KEY=ulDoUo3BcZ0HK4P4
            - MINIO_SECRET_KEY=JH4f31eN8YAg9kn3BQUsh3cuoVGPNedo
        command: server --address 0.0.0.0:9000 /data --console-address=":9001"

volumes:
    mongoUser:
    mongoStatus:
    mongoStory:
