version: "3"

services:
    nginx:
        image: rakib3004/frontend
        build: .
        restart: unless-stopped
        ports:
            - 100:100
        depends_on:
            - userservice
            - statusservice
            - storyservice

    userservice:
        image: rakib3004/userservice
        build: ./UserService
        restart: unless-stopped
        depends_on:
            - userdb

    userdb:
        image: mongo:4.0-xenial
        # ports: 
        #     - 27018:27017
        restart: unless-stopped
        volumes:
            - mongoUser:/data/db
    
    statusservice:
        image: rakib3004/statusservice
        build: ./StatusService
        restart: unless-stopped
        depends_on:
            - statusdb

    statusdb:
        image: mongo:4.0-xenial
        # ports: 
        #     - 27019:27017
        restart: unless-stopped
        volumes:
            - mongoStatus:/data/db

    storyservice:
        image: rakib3004/storyservice
        build: ./StoryService
        restart: unless-stopped
        depends_on:
            - storydb
            - storyobjectdb

    storydb:
        image: mongo:4.0-xenial
        # ports: 
        #     - 27020:27017
        restart: unless-stopped
        volumes:
            - mongoStory:/data/db

    storyobjectdb:
        image: minio/minio
        ports:
            - 9000:9000
            - 9001:9001
        environment:
            - MINIO_ACCESS_KEY=minioadmin
            - MINIO_SECRET_KEY=minioadmin
        command: server --address 0.0.0.0:9000 /data --console-address=":9001"

volumes:
    mongoUser:
    mongoStatus:
    mongoStory:
